# Generated by Django 3.2.5 on 2021-07-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDeskapp', '0004_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='user',
        ),
    ]
